services:

  caddy:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 3000:3000
    # volumes:
    #   - ./nginx.conv:/etc/nginx/templates/nginx.conf.template
    #   - ./app/dist:/usr/share/nginx/html
    environment:
      API_HOST: http://host.docker.internal:8000
      KEYCLOAK_URL: http://127.0.0.1:8080
      KEYCLOAK_REALM: cron-mon-io
      KEYCLOAK_CLIENT_ID: cron-mon

  dev:
    build:
      dockerfile: ./Dockerfile
      context: .
      target: builder
    container_name: cron-mon-app-npm
    stdin_open: true
    tty: true
    volumes:
      - ./app:/usr/cron-mon/app
    ports:
      - 3000:3000
    command: npm run dev
    networks:
      - default
      - cron-mon-network

networks:
  cron-mon-network:
    driver: bridge
    name: cron-mon-network
