services:

  caddy:
    image: public.ecr.aws/docker/library/caddy:2.9
    ports:
      - 3000:3000
    volumes:
      - ./app/Caddyfile:/etc/caddy/Caddyfile
      - ./app/dist:/srv
      - caddy_data:/data
      - caddy_config:/config
    environment:
      API_HOST: http://host.docker.internal:8000
      KEYCLOAK_URL: http://127.0.0.1:8080
      KEYCLOAK_REALM: cron-mon-io
      KEYCLOAK_CLIENT_ID: cron-mon

  dev:
    build:
      dockerfile: ./Dockerfile
      context: .
      target: builder
    container_name: cron-mon-app-npm
    stdin_open: true
    tty: true
    volumes:
      - ./app:/usr/cron-mon/app
    ports:
      - 3000:3000
    command: npm run dev
    networks:
      - default
      - cron-mon-network

networks:
  cron-mon-network:
    driver: bridge
    name: cron-mon-network

volumes:
  caddy_data:
  caddy_config:
