on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "app/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run lint checks
        run: npm run lint

  type-check:
    name: Type check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "app/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run type checks
        run: npm run type-check

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "app/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  build-and-push-image:
    name: Build and push container image to ghcr.io
    needs: [lint, type-check, test]
    if: ${{ github.ref_name == 'main' }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: cron-mon-io/ghcr-actions/.github/workflows/build-and-push.yml@main
